baseURL = "http://dmipopov.github.io/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Dmitry Popov"
tags = ["dmitry", "popov", "devops", "golang", "Дмитрий", "Попов"]
theme = "gokarna"

enableRobotsTXT = true

pygmentsStyle = "dracula"

[params]
  avatarURL = "/face.jpeg"
  avatarSize = "size-l"
  description = "Hi, I am a 4th year cybersec student at HSE and DevOps engineer. This blog is for fun, do not take it too seriously."
  socialIcons = [
      {name = "linkedin", url = "https://linkedin.com/in/dmipopov/"},
      {name = "github", url = "https://github.com/dmipopov/"},
      {name = "telegram", url = "https://t.me/holyshrimp"},
      {name = "gmail", url = "mailto:dmipopov01@gmail.com"},
    ]
  customHeadHTML = '''<meta name="google-site-verification" content="paFPDfNajAuHa6zUeXNw9bLL7S8pder-EknsuBxDoBM" />'''
  metaKeywords = ["blog", "dmipopov", "devops", "golang", "Дмитрий", "Попов"]
  showPostsOnHomePage = "recent"
  footer = "Dmitry Popov"
  accentColor = "#ee81c2"
[menu]
  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "posts"

    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    #pre = "<span data-feather='file-text'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    #pre = "<span data-feather='tag'></span>"
    weight = 2

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/files/popov_devops.pdf"
    #pre = "<span data-feather='briefcase'></span>"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/dmipopov"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/dmipopov/"
    weight = 5

    pre = "<span data-feather='linkedin'></span>"
